### ISSUE TITLE
希望能支持页脚（页码）

### ISSUE THREAD

**Issue by rny** [Luna-CY/go-office#1]
已经用上了，简单直接很好用，谢谢！

希望能支持在页脚显示页码，现在生成比较长的内容时候也没有页码，打印起来会很难受。

**Comment by Luna-CY** [comment]
行，我找个时间加上，以前没人用，这项目都快放弃了

**Comment by Luna-CY** [comment]
Footer添加了一个方法AddPageNum用于设置页码

**Comment by rny** [comment]
已经用上了，谢谢！
